<template>
    <div class="container--longtext">
        <h1>PRIVACY POLICY</h1>

        <ol>
            <li>
                <h2>Information We Collect</h2>
                <p>
                    The Application operates entirely within your browser and
                    does not collect, store, or transmit personal data to
                    external servers. The only data processed are the images you
                    capture using the Application.
                </p>
            </li>
            <li>
                <h2>Local Storage of Images</h2>
                <p>
                    All images generated by the Application are stored locally
                    in your browser&apos;s IndexedDB. These images are not
                    uploaded to any server or cloud storage and remain
                    accessible only on the device where they were created.
                </p>
            </li>
            <li>
                <h2>How We Use Your Data</h2>
                <p>
                    Since the Application does not transmit data outside of your
                    browser, we do not use your images or any other personal
                    data for analytics, advertising, or any other purposes.
                </p>
            </li>
            <li>
                <h2>Data Retention and Deletion</h2>
                <ol>
                    <li>
                        Your images remain stored in IndexedDB unless you
                        manually clear your browser storage or delete them
                        within the Application.
                    </li>
                    <li>
                        Deleting your browser data will remove all stored images
                        permanently.
                    </li>
                </ol>
            </li>
            <li>
                <h2>Third-Party Services</h2>
                <p>
                    The Application does not use third-party analytics,
                    advertisements, or external cloud storage. All processing
                    happens within your device.
                </p>
            </li>
            <li>
                <h2>Your Privacy Rights</h2>
                <p>
                    Because no personal data is collected or stored beyond your
                    local device, there are no external requests required to
                    access, update, or delete your data.
                </p>
            </li>
            <li>
                <h2>Security Measures</h2>
                <p>
                    Since all data remains on your local device, security is
                    dependent on your browser and device settings. We recommend
                    keeping your browser updated and using secure browsing
                    practices.
                </p>
            </li>
            <li>
                <h2>Changes to This Policy</h2>
                <p>
                    We may update this Privacy Policy from time to time. Any
                    changes will be reflected within the Application. Continued
                    use of the Application after any modifications constitutes
                    acceptance of the revised Privacy Policy.
                </p>
            </li>
            <!-- <li>
                <h2>Contact Us</h2>
                <p>
                    If you have any questions about this Privacy Policy, you can
                    contact us at [Your Contact Email or Website].
                </p>
            </li> -->
        </ol>
    </div>
</template>

<style scoped>
    .container--longtext {
        width: 75%;
        margin: 0 auto;
    }

    h1 {
        text-transform: uppercase;
        font-weight: 700;
    }

    h1,
    h2 {
        font-family: "Josefin Slab", serif;
        font-size: var(--step-2);
    }

    li:not(:last-child) {
        margin-bottom: var(--space-s);
    }

    ol li,
    p {
        font-family: "Josefin Sans", serif;
        font-size: var(--step-0);
    }
</style>
